### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by sarahholder** [nss-evening-cohort-11/nutshell-droids#11]
## User Story
As a user, I would like to see a navbar.

## AC
**WHEN** the page loads
**THEN** I should see a navbar
**AND** it should have the PanAm logo
**AND** it should have a red logout button
**AND** it should have a link that says Dashboard
**AND** none of the links/buttons should work.

## Dev Notes
* in index.html make div with id = my-navbar
* Use bootstrap navbar - https://getbootstrap.com/docs/4.3/components/navbar/
* make a component called `myNavbar` - export `printNavbar`
* `printNavbar` builds up a bootstrap navbar domString
* call `printToDom('my-navbar', domString)`

**Comment by sarahholder** [comment]
![image](https://user-images.githubusercontent.com/59459651/79284503-7447d600-7e80-11ea-9cb1-897a156dae61.png)

**Comment by stephencastaneda** [comment]
`
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">
    <img src="/docs/4.0/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
    Bootstrap
  </a>
</nav>`

**Comment by zoeames** [comment]
Updated wireframe
![image](https://user-images.githubusercontent.com/8093647/79396441-8f2e4f00-7f41-11ea-9ea3-759e021105bb.png)
