### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/nutshell-droids#13]

**Comment by stephencastaneda** [comment]
![Screen Shot 2020-04-14 at 9 32 19 AM](https://user-images.githubusercontent.com/59769978/79285955-bbd06100-7e84-11ea-9d81-d1aeccfd91a6.png)
![Screen Shot 2020-04-14 at 9 32 36 AM](https://user-images.githubusercontent.com/59769978/79285967-c0951500-7e84-11ea-9547-07221e40ba08.png)
![Screen Shot 2020-04-14 at 9 32 48 AM](https://user-images.githubusercontent.com/59769978/79285973-c4289c00-7e84-11ea-8efd-8f645ffe8479.png)
![Screen Shot 2020-04-14 at 9 33 00 AM](https://user-images.githubusercontent.com/59769978/79285978-c7bc2300-7e84-11ea-8598-5163e1eb23b5.png)
![Screen Shot 2020-04-14 at 9 33 12 AM](https://user-images.githubusercontent.com/59769978/79285987-d0145e00-7e84-11ea-98d5-1467c2ba7b89.png)

**Comment by zoeames** [comment]
Updated Navbar (user logged in)
![image](https://user-images.githubusercontent.com/8093647/79396461-9f462e80-7f41-11ea-92ed-42942524fb17.png)
