### ISSUE TITLE
Seed Data - Crew

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/nutshell-droids#28]
## User Story
As a developer, I need see data for the foods collection

## AC
*WHEN* i look at the repo
*THEN* there should be a foods.json file in the the db folder
*AND* it should have 12 foods (3 for each of us)

## Dev Notes
*sample food item
```
{
	"food1": {
		"uid": "12345",
		"imageUrl": "https://images-na.ssl-images-amazon.com/images/I/71Wb5tAxlwL._SL1500_.jpg",
		"name": "pretzles",
		"type": "snack",
		"price": 0,
		"isComplementary": true
	}
}
```

**Comment by kenymc1** [comment]
{
	"crew1": {
		"uid": "1",
		"name": "Kristin Bell",
		"base city": "Nashville",
		"position": "Flight Attendant",
		"hire date": "02/24/2019",
		"img": "https://drive.google.com/open?id=1FeMjXxZCzSXJz7JqhZNOthGZ9cFgC9iW"
	},
	"crew2": {
		"uid": "2",
		"name": "Johnathan Smart",
		"base city": "Chicago",
		"position": "Flight Attendant",
		"hire date": "08/28/2015",
		"img": "https://drive.google.com/open?id=1woz8RZ3pizD6wZIoWGZ7vIMa5h7t0YFN"
	},
	"crew3": {
		"uid": "3",
		"name": "Bill Johnson",
		"base city": "Ohio",
		"position": "Pilot",
		"hire date": "07/21/2015",
		"img": "https://drive.google.com/open?id=1Jb-UG6VX_62dFEuSIAj7Mr6csFMfhiCJ"
	},
	"crew4": {
		"uid": "Stephen",
		"name": "Will Rough",
		"base city": "Nashville",
		"position": "Mechanic",
		"hire date": "03/16/2016",
		"img": "https://drive.google.com/open?id=1qlevmQHN39_ZtILycd2YCgzzc-0TYv02"
	},
	"crew5": {
		"uid": "Stephen",
		"name": "Ron Freeman",
		"base city": "Nashville",
		"position": "Co-Pilot",
		"hire date": "09/21/2013",
		"img": "https://drive.google.com/open?id=17IhRk1k0DOKVgTo3p-XOe_KE9knjiUlw"
	},
	"crew6": {
		"uid": "Stephen",
		"name": "Kent Bravo",
		"base city": "Houston",
		"position": "Pilot",
		"hire date": "10/13/2015",
		"img": "https://drive.google.com/open?id=1x68q5OFB8n8hHUZrV6ZT_77mdPuUit9k"
	}
{
	"crew7": {
		"uid": "Sarah",
		"name": "Lana Pratt",
		"base city": "Nashville",
		"position": "Flight Attendant",
		"hire date": "02/24/2019",
		"img": "https://drive.google.com/open?id=1ztFor144ZCAVWttL7lmGIN7IXjV4MNUr"
	},
	"crew8": {
		"uid": "Sarah",
		"name": "Johnathan Smart",
		"base city": "Chicago",
		"position": "Flight Attendant",
		"hire date": "08/28/2015",
		"img": "https://drive.google.com/open?id=1VuwrMOzHKuEnGnvjEGy8hRRz4RL2zXJK"
	},
	"crew9": {
		"uid": "Sarah",
		"name": "Ben James",
		"base city": "Ohio",
		"position": "Pilot",
		"hire date": "07/21/2015",
		"img": "https://drive.google.com/open?id=1DRFoOpB6fer9q4r4M-Sw7uaveABkzsc2"
	},
	"crew10": {
		"uid": "Zoe",
		"name": "Bill Wright",
		"base city": "Memphis",
		"position": "Mechanic",
		"hire date": "03/16/2016",
		"img": "https://drive.google.com/open?id=18O0y8Brtu3g4xEb9CTIWAKJ-iQYaamoQ"
	},
	"crew11": {
		"uid": "Zoe",
		"name": "Randy Ford",
		"base city":"Orlando",
		"position": "Co-Pilot",
		"hire date": "11/22/2013",
		"img": "https://drive.google.com/open?id=1Gd38ab6_Gxw8ffvcNbeFPYBW8D0QmDeY"
	},
	"crew12": {
		"uid": "Zoe",
		"name": "Kendall Best",
		"base city": "Louisville",
		"position": "Pilot",
		"hire date": "10/12/2015",
		"img": "https://drive.google.com/open?id=1NkkayewVGp2auqSHpHzmsZGei-2VZWWt"
	}
}
