### ISSUE TITLE
Airports - Read

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/nutshell-droids#31]
## User Story
As a user, I should be able to view all airports that are available for use by PanAm.

## AC
**WHEN** looking at the airports "page"
**THEN** I should see all the airports

## Dev Notes
* create a div in index.html with an id of `hub` and a class of hide
* update `authData.checkLoginStatus` and add removeClass into the if statement for `hub`.
* * create a `hub` component with a function called `printAirports` add this function to the export default
* `printAirports` should call `airportsData.getAllAirports`
*  airportsData.getAllAirports` should make an `axios.get` to `airports.json`
* on failure of `airportsData.getAllAirports` promise `console.error('unable to get airports')`
* on success of `airportsData.getAllAirports` promise  should build up a `domString` with a h2 tag and loop over all the airports and for each food call `airportComponent.buildAirport`
* Create airportComponent - make `buildAirport` function and export it
* `buildAirport` should return a domString that is a card for that Airport
* `printAirports` should call `utils.printToDom` and pass in `hub` as the id

**Comment by sarahholder** [comment]
We listed to add and remove the class based on logged in out logged out status-- but we also talked about users being able to still see the data even when they are not logged in.
