### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by kenymc1** [nss-evening-cohort-11/nutshell-droids#9]
## User Story
As a user, i want this site to be real.

## AC
**WHEN** I want to look at this site
**THEN** I can go to a firebase link
**AND** don't have to run it locally

## Dev Notes
* `firebase init` - to set up the project
* Deploy project in whatever state its in

**Comment by zoeames** [comment]
Deploy notes:  https://github.com/nss-nightclass-projects/Night-Class-Resources/blob/master/book-3-data-driven-applications/chapters/firebase-deploy.md
